nfs-server-provisioner:
  persistence:
    enabled: true
    storageClass: standard
    size: 10Gi
  storageClass:
    defaultClass: false

# SSH Jumphost settings
gitAuth:
  host: 'github.com'
  organisation: ''
  apiToken: ''
