

nfs-server-provisioner:
  persistence:
    enabled: true
    storageClass: standard
    size: 10Gi
  storageClass:
    defaultClass: false

# SSH Jumphost settings
gitAuth:
  host: 'github.com'
  organisation: 'you need to pass in a value for shell.gitAuth.organisation to your helm chart'
  apiToken: 'you need to pass in a value for shell.gitAuth.apiToken to your helm chart'
