---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs
  labels:
    k8s-app: filebeat
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors: # this may not work 
        - drop_event.when.or:
          - contains:
              message: "kube-probe"
        - add_kubernetes_metadata:
            in_cluster: true