---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-splash
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Release.Name }}-splash
      prefix: /
      service: {{ .Release.Name }}-splash:80
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Release.Name }}-no-robots
      prefix: /robots.txt
      rewrite: /robots/deny/robots.txt
      service: {{ .Release.Name }}-splash:80
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    name: {{ .Release.Name }}-splash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-splash
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-splash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-splash
    spec:
      containers:
      - image: "wunderio/silta-splash"
        name: nginx